
server:
  port: 8080

binance:
  ws-url: wss://stream.binance.com:9443/stream
  symbols: btcusdt, ethusdt

ohlc:
  timeframes: 15, 30, 60

alerts:
  price-thresholds: "{ 'btcusdt': { 'upper': 100000, 'lower': 85000 } }"
  percent-change: "{ 'ethusdt': { 'timeframe': 15, 'candles': 5, 'percent': 2.5 } }"

#  price-thresholds:
#    btcusdt:
#      upper: 50000
#      lower: 40000
#  percent-change:
#    btcusdt:
#      timeframe: 15
#      candles: 4
#      percent: 1.5


spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/marketanalyse
    username: marketanalyse
    password: ${CRYPASS}
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
logging:
  level:
    root: INFO
#    com.example.cryptoanalyzer: DEBUG
