
server:
  port: 8080

binance:
  ws-url: wss://stream.binance.com:9443/stream
  symbols: btcusdt, ethusdt

ohlc:
  timeframes: 15, 30, 60

alerts:
  price-thresholds: "{ 'btcusdt': { 'upper': 900000, 'lower': 85000 } }"
  percent-change: "{ 'ethusdt': { 'timeframe': 15, 'candles': 5, 'percent': 2.5 } }"

#  price-thresholds:
#    btcusdt:
#      upper: 50000
#      lower: 40000
#  percent-change:
#    btcusdt:
#      timeframe: 15
#      candles: 4
#      percent: 1.5


spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:marketanalyse
    driver-class-name: org.h2.Driver
    username: sa
    password: password
#    url: jdbc:postgresql://localhost:5433/marketanalyse
#    username: marketanalyse
#    password: ${CRYPASS}
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
logging:
  level:
    root: INFO
#    com.example.cryptoanalyzer: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  packages-to-scan: com.example.cryptoanalyzer.web
